name: DeathBan
version: ${project.version}
main: exodian.me.deathban.DeathBan
api-version: 1.13
authors: [SamPom100]
description: Bans people upon death.
website: github.com/SamPom100


permissions:
  deathban.immune:
    description: Renders you immune from the plugin.
    default: false